config/routes.rb
Rails.application.routes.draw do
  root 'cities#show'

  namespace :admin do
    get 'dashboard/index', to: 'dashboard#index', as: :dashboard

    get 'moderation/index', to: 'moderation#index', as: :moderation
    post 'moderation/status_update', to: 'moderation#status_update'
    post 'moderation/company', to: 'moderation#company'
  end

  namespace :profiles do
    resources :bikes, except: [:destroy, :show]
    get 'bikes/:id', to: 'bikes#show', constraints: { id: /\d+/ }

    post 'bikes/:id/restore', to: 'bikes#restore', as: :bike_restore
    post 'bikes/:id/close', to: 'bikes#close', as: :bike_close

    resources :pictures, only: :destroy
    post 'pictures/upload', to: 'pictures#upload'
    patch 'pictures/upload', to: 'pictures#upload'
  end

  get '/bikes/:id', to: redirect('/')

  get '/cities', to: 'cities#index'
  get '/cities/new', to: 'cities#new'
  get '/:city_id/bikes', to: 'cities#show', as: :city
  get '/:city_id/bikes/:id', to: 'bikes#show', as: :bike

  get '/bikes/:id/phone', to: 'bikes#phone'
  get '/bikes/:id/email', to: 'bikes#email'

  get 'phones/send_sms_code', to: 'phones#send_sms_code'
  put 'phones/:id', to: 'phones#update'

  resources :favorites, only: :index do
    post 'set', as: 'set'
    post 'unset', as: 'unset'
  end

  resources :feedback, only: [:create, :new]

  devise_for :users, controllers: { registrations: "registrations" }
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  is_impressionable
  extend Enumerize

  belongs_to :user
  belongs_to :city

  enumerize :status, in: [:on_moderation, :approved, :closed, :rejected], default: :on_moderation
  enumerize :function, in: [
    :mtb,
    :road,
    :hybrid,
    :street_dirt,
    :bmx,
    :downhill,
    :trial,
    :touring,
    :highway,
    :fixed,
    :fat,
    :tandem,
    :recumbent,
    :cruiser,
    :tricycle,
    :exotic
  ]
  enumerize :suspension, in: [:hard_tail, :full_tail, :no_suspension]
  enumerize :age, in: [:kid, :junior, :adult]
  enumerize :sex, in: [:unisex, :female]
  enumerize :gears, in: 33.downto(1).to_a
  enumerize :wheels, in: ['29', '28', '27.5', '27', '26', '24', '20', '18', '16', '14', '12']

  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :title,
            :function,
            :price,
            :pictures,
            :user,
            :city_id,
            presence: true

  validates_numericality_of :price

  before_update :drop_moderation

  scope :approved, -> { where(status: :approved) }
  scope :on_moderation, -> { where(status: :on_moderation) }
  scope :without_companies, -> { includes(:user).where(users: { is_company: false }) }
  scope :parsed, -> { where.not(original_url: nil) }

  def phone
    user.phone.number
  end

  def email
    user.email
  end

  def price=(new_price)
    self[:price] = new_price.to_s.gsub(/\s+/, '').to_i if new_price.present?
  end

  private

  def drop_moderation
    if title_changed? || description_changed?
      self.status = :on_moderation
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug, use: :slugged

  belongs_to :department
  has_many :bikes
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :cities
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
  validates :title, :description, :user, presence: :true
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :number
  validates_uniqueness_of :number, conditions: -> { where(activated: true).where.not(sms_key: nil) }

  before_validation :phone_format
  before_update :drop_activation

  private

  def self.generate_key
    rand(1111..9999)
  end

  def phone_format
    self.number = number.gsub(/[\s()-]/, '') if number.present?
  end

  def drop_activation
    self.activated = 'false' if number_changed?
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :bike

  has_attached_file :img,
                    styles: {
                        big: '1680x1050>',
                        medium_l: "600x500#",
                        medium: "300x250#",
                        medium_s: "200x250#",
                        thumb: "100x150#"
                    },
                    convert_options: {
                        all: "-gravity south -crop 100%x100%+0+50 +repage"
                    }

  validates_attachment_presence :img
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :img, :less_than => 10.megabytes
end

app/models/proxy.rb
class Proxy < ActiveRecord::Base
  validates_uniqueness_of :ip

  scope :active, -> { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enumerize :role, in: [:user, :admin], default: :user

  has_many :bikes, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  has_one :phone, dependent: :destroy
  accepts_nested_attributes_for :phone, allow_destroy: true

  validates :email, :name, presence: true

  after_create do
    AdminMailer.new_user.deliver_later unless email.include?('@bikebook.ru')
  end

  def update_without_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  impressionist actions: [:show]

  def show
    @bike = Bike.approved.without_companies.find_by!(id: params[:id])
    @similar = similar(@bike)
    impressionist(@bike)
    render partial: 'shared/bike_show', locals: {bike: @bike} if params[:modal]
  rescue ActiveRecord::RecordNotFound
    if params[:modal]
      render json: { message: t(:bike_not_found) }, status: 400
    else
      redirect_to(root_path, flash: {error: t(:bike_not_found)})
    end
  end

  def phone
    render json: { number: Bike.find_by(id: params[:id]).phone }
  end

  def email
    render json: { email: Bike.find_by(id: params[:id]).email }
  end

  def similar(bike)
    price = bike.price * 0.20
    Bike.approved.without_companies.includes(:city, :pictures).where(
      function: bike.function,
      price: (bike.price - price)..(bike.price + price),
      city_id: bike.city_id
    ).where.not(id: bike.id).limit(4)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def human_price(price)
    number_with_delimiter(price, delimiter: " ") + " руб."
  end
end

app/helpers/bikes_helper.rb
module BikesHelper
  def pretty_date(date)
    if date.today?
      'Размещено сегодня'
    elsif date.to_date == Date.yesterday
      'Размещено вчера'
    else
      l(date, format: '%e %B %Y')
    end
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
  def bookmarked(id: bike.id)
    if cookies[:favorites].present?
      cookies_ary = JSON.parse(cookies[:favorites])
      'set' if cookies_ary.include?(id.to_s)
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:div, msg) }.join
    html = <<-HTML
    <div class="flash">
      <div class="message alert">#{messages}</div>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/moderations_helper.rb
module ModerationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.slim
doctype html
html data-modal-open='false'
  head
    title = yield(:title).presence || "Б/У велосипеды: детские, горные, городские, BMX, электрические и др. - BikeBook.ru"
    meta name="description" content="#{yield(:description).presence || 'Доска частных объявлений по продаже и покупке бу велосипедов по всей России - BikeBook.ru'}"
    meta charset="UTF-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta name="google-site-verification" content="3dceaRKPXKHOjV0qjbwxHvXdmA4J6QmhKBTMdm9ef1s"
    meta name="msvalidate.01" content="FE20663D606CD408EE67A91AEC8AF7CB"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body class="#{controller_name} #{action_name}"
    = render 'shared/modal'
    #wrapper.wrapper
      #container
        = render 'shared/notice'
        = render 'shared/flash'
        = render 'shared/header'
        = render 'shared/subheader'
        = yield
    .wrapper
      = render 'shared/footer'
      = render 'shared/counter'

app/views/shared/_bike_index.html.slim
= link_to bike_path(bike.city, bike), class: 'bike_index', data: { id: bike.id, behavior: 'modal', root: '' } do

  .bike_index__add_to_favorites data-behavior='add_to_favorites' data-loading='false' class=bookmarked(id: bike.id)
  - if policy(bike).admin?
    .bike_index__not_a_bike.bike_index__services_btn data-behavior='set_status' data-status='rejected' data-loading='false'
    .bike_index__send_on_moderation.bike_index__services_btn data-behavior='set_status' data-status='on_moderation' data-loading='false'

  .bike_index__image data-image='' data-loading='false' style="background-image: url(#{bike.pictures.any? ? bike.pictures.order(img_updated_at: :asc).first.img.url(:medium) : false})"

  .bike_index__price
    - if bike.price > 0
      = human_price(bike.price)
    - else
      | нет цены
  .bike_index__footer
    .date = pretty_date(bike.created_at)
    .dot &bull;
    .city= bike.city.name

app/views/shared/_bike_show.html.slim
= content_for(:title, "#{bike.try(:title)} б/у, цена #{bike.try(:price)} руб - BikeBook.ru")
= content_for(:description, "#{bike.try(:title)} б/у, по цене #{bike.try(:price)} руб в городе #{bike.try(:city).try(:name)}")

.bike_show data-id="#{bike.id}" data-root=''
  .bike_show__close data-behavior='modal_close'
  .bike_show__header
    .title
      h1 = bike.title
      .info
        span Добавлено: #{pretty_date(bike.created_at)}
        span = link_to "#{bike.city.department.name}, #{bike.city.name}", city_path(bike.city), data: { no_turbolink: true }
        span.eye #{bike.impressionist_count} (#{bike.impressionist_count(start_date: DateTime.now.beginning_of_day, end_date: DateTime.now.end_of_day)} сегодня)
    .price
      - if bike.price > 0
        = human_price(bike.price)
      - else
        | нет цены
    .services
      .add_to_favorites data-behavior='add_to_favorites' data-loading='false' class=bookmarked(id: bike.id)
  .bike_show__subheader
    .owner
      span Продавец:
      = bike.user.name
    .contacts
      - if bike.user.phone.activated
        span.contact: .show_phone data-behavior='show_contact_phone' Показать телефон
      - unless bike.original_url.present?
        span.contact: .show_email data-behavior='show_contact_email' Показать почту
  .bike_show__main
    .image
      .fotorama
        - bike.pictures.order(img_updated_at: :asc).each do |picture|
          = link_to nil, picture.img.url(:big), data: {thumb: picture.img.url(:thumb)}
    .config
      - if policy(bike).admin?
        = render 'shared/moderator_area', bike: bike
      - else
        table
          tr
            td.description Тип велосипеда:
            td= link_to t("enumerize.defaults.function.#{bike.function}"), "/?function=#{bike.function}", data: { no_turbolink: true }
          tr
            td.description Подвеска:
            td #{bike.suspension.present? ? t("enumerize.defaults.suspension.#{bike.suspension}") : '-'}
          tr
            td.description Возраст:
            td #{bike.age.present? ? t("enumerize.defaults.age.#{bike.age}") : '-' }
          tr
            td.description Пол:
            td #{bike.sex.present? ? t("enumerize.defaults.sex.#{bike.sex}") : '-' }
          tr
            td.description Количество скоростей:
            td = bike.gears || '-'
          tr
            td.description Размер колес:
            td = bike.wheels || '-'
          tr
            td.description Электрический:
            td #{bike.electric ? 'Да' : 'Нет' }
          tr
            td.description Складной:
            td #{bike.folding ? 'Да' : 'Нет' }
  .bike_show__footer
    - if bike.description.present?
      .bike_group
        div Описание:
        noindex = sanitize(bike.description, tags: %w[br \n])
  - if @similar.present?
    .bike_show__similar
      .header
        h3 Похожие объявления в городе #{bike.city.name}
      - @similar.each do |similar|
        = render 'shared/bike_index', bike: similar

app/views/shared/_counter.html.slim
javascript:
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function () {
      try {
        w.yaCounter34532240 = new Ya.Metrika({
          id: 34532240,
          clickmap: true,
          trackLinks: true,
          accurateTrackBounce: true,
          webvisor: true,
          trackHash: true
        });
      } catch (e) {
      }
    });

    var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () {
              n.parentNode.insertBefore(s, n);
            };
    s.type = "text/javascript";
    s.async = true;
    s.src = "https://mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
      d.addEventListener("DOMContentLoaded", f, false);
    } else {
      f();
    }
  })(document, window, "yandex_metrika_callbacks");


noscript
  div
    img alt="" src="https://mc.yandex.ru/watch/34532240" style=("position:absolute; left:-9999px;") /

app/views/shared/_flash.html.slim
- unless flash.empty?
  .flash
    .inner_content
      - flash.each do |type, message|
        - next if message.blank?
        div class="message #{type}" = message.strip

app/views/shared/_footer.html.slim
#footer
  .inner_content
    = render_navigation :context => :footer, :expand_all => false, renderer: :links

app/views/shared/_header.html.slim
#header
  .inner_content
    .mobile_nav_trigger
      .icon-menu
    = render_navigation expand_all: false, renderer: :links

app/views/shared/_modal.html.slim
.modal
  .modal__cloak data-behavior='modal_close'
  .modal__content data-behavior='modal_content'

app/views/shared/_moderator_area.html.slim
.moderator_area
  = simple_form_for [:profiles, bike], namespace: bike.id, remote: true do |f|
    .form_group
      = f.input :function, as: :radio_buttons, collection: Bike.function.options, include_blank: 'Выбрать', label: false
    .form_group
      = f.input :suspension, as: :radio_buttons, collection: Bike.suspension.options, include_blank: 'Выбрать', label: false
    .form_group
      = f.input :age, as: :radio_buttons, collection: Bike.age.options, include_blank: 'Возраст', label: false
    .form_group
      = f.input :sex, as: :radio_buttons, collection: Bike.sex.options, include_blank: 'Пол', label: false
    .form_group
      = f.input :folding, as: :boolean
      = f.input :electric, as: :boolean
    .form_group
      = f.input :gears, collection: Bike.gears.options, include_blank: 'Кол-во скоростей', label: false
      = f.input :wheels, collection: Bike.wheels.options, include_blank: 'Диаметр колес', label: false

  .actions
    span.approve data-behavior='set_status' data-status='approved'
    span.reject data-behavior='set_status' data-status='rejected'
    span.on_moderation data-behavior='set_status' data-status='on_moderation'
    span.company data-behavior='set_status' data-status='company'

  .owner_bikes
    - bike.user.bikes.each do |b|
      - next if bike.id == b.id
      = link_to b.title, bike_path(b.city, b)
      span #{' / '}

app/views/shared/_notice.html.slim
- if user_signed_in? && current_user.phone.activated == false
  .phone_notice
    .inner_content
      | Ваш номер телефона не подтвержден.
        Подтверждение телефона необходимо для указания его в качестве контактных данных при подаче объявления.
        Подтвердить телефон вы можете в разделе #{link_to 'Мой профиль', edit_user_registration_path}

app/views/shared/_subheader.html.slim
#subheader
  .inner_content
    .left
      - if @city.present?
        h1 Продажа б/у велосипедов в городе #{@city.name}
      - else
        h1 Продажа б/у велосипедов
    .right
      = link_to "Избранное <span class='show_favorites_size' data-behavior='show_favorites_size'>#{favorites_size}</span>".html_safe, favorites_path, class: "show_favorites #{'selected' if params[:controller] == 'favorites'}"