config/routes.rb
Rails.application.routes.draw do
  root 'cities#show'

  namespace :admin do
    get 'dashboard/index', to: 'dashboard#index', as: :dashboard

    get 'moderation/index', to: 'moderation#index', as: :moderation
    post 'moderation/status_update', to: 'moderation#status_update'
    post 'moderation/company', to: 'moderation#company'
  end

  namespace :profiles do
    resources :bikes, except: [:destroy, :show]
    get 'bikes/:id', to: 'bikes#show', constraints: { id: /\d+/ }

    post 'bikes/:id/restore', to: 'bikes#restore', as: :bike_restore
    post 'bikes/:id/close', to: 'bikes#close', as: :bike_close

    resources :pictures, only: :destroy
    post 'pictures/upload', to: 'pictures#upload'
    patch 'pictures/upload', to: 'pictures#upload'
  end

  get '/bikes/:id', to: redirect('/')

  get '/cities', to: 'cities#index'
  get '/cities/new', to: 'cities#new'
  get '/:city_id/bikes', to: 'cities#show', as: :city
  get '/:city_id/bikes/:id', to: 'bikes#show', as: :bike

  get '/bikes/:id/phone', to: 'bikes#phone'
  get '/bikes/:id/email', to: 'bikes#email'

  get 'phones/send_sms_code', to: 'phones#send_sms_code'
  put 'phones/:id', to: 'phones#update'

  resources :favorites, only: :index do
    post 'set', as: 'set'
    post 'unset', as: 'unset'
  end

  resources :feedback, only: [:create, :new]

  devise_for :users, controllers: { registrations: "registrations" }
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  is_impressionable
  extend Enumerize

  belongs_to :user
  belongs_to :city

  enumerize :status, in: [:on_moderation, :approved, :closed, :rejected], default: :on_moderation
  enumerize :function, in: [
    :mtb,
    :road,
    :hybrid,
    :street_dirt,
    :bmx,
    :downhill,
    :trial,
    :touring,
    :highway,
    :fixed,
    :fat,
    :tandem,
    :recumbent,
    :cruiser,
    :tricycle,
    :exotic
  ]
  enumerize :suspension, in: [:hard_tail, :full_tail, :no_suspension]
  enumerize :age, in: [:kid, :junior, :adult]
  enumerize :sex, in: [:unisex, :female]
  enumerize :gears, in: 33.downto(1).to_a
  enumerize :wheels, in: ['29', '28', '27.5', '27', '26', '24', '20', '18', '16', '14', '12']

  has_many :pictures, dependent: :destroy
  accepts_nested_attributes_for :pictures, allow_destroy: true

  validates :title,
            :function,
            :price,
            :pictures,
            :user,
            :city_id,
            presence: true

  validates_numericality_of :price

  before_update :drop_moderation

  scope :approved, -> { where(status: :approved) }
  scope :on_moderation, -> { where(status: :on_moderation) }
  scope :without_companies, -> { includes(:user).where(users: { is_company: false }) }
  scope :parsed, -> { where.not(original_url: nil) }

  def phone
    user.phone.number
  end

  def email
    user.email
  end

  def price=(new_price)
    self[:price] = new_price.to_s.gsub(/\s+/, '').to_i if new_price.present?
  end

  private

  def drop_moderation
    if title_changed? || description_changed?
      self.status = :on_moderation
    end
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  impressionist actions: [:show]

  def show
    @bike = Bike.approved.without_companies.find_by!(id: params[:id])
    @similar = similar(@bike)
    impressionist(@bike)
    render partial: 'shared/bike_show', locals: {bike: @bike} if params[:modal]
  rescue ActiveRecord::RecordNotFound
    if params[:modal]
      render json: { message: t(:bike_not_found) }, status: 400
    else
      redirect_to(root_path, flash: {error: t(:bike_not_found)})
    end
  end

  def phone
    render json: { number: Bike.find_by(id: params[:id]).phone }
  end

  def email
    render json: { email: Bike.find_by(id: params[:id]).email }
  end

  def similar(bike)
    price = bike.price * 0.20
    Bike.approved.without_companies.includes(:city, :pictures).where(
      function: bike.function,
      price: (bike.price - price)..(bike.price + price),
      city_id: bike.city_id
    ).where.not(id: bike.id).limit(4)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
end

app/controllers/profiles/bikes_controller.rb
class Profiles::BikesController < ApplicationController
  before_action :load_city
  before_action :drop_session_pictures, except: [:create, :update, :edit]

  def index
    @bikes = policy_scope([:profiles, Bike]).order(
      "status = 'rejected' DESC",
      "status = 'approved' DESC",
      "status = 'on_moderation' DESC",
      "status = 'closed' DESC"
    )
  end

  def new
    @bike = Bike.new
    authorize [:profiles, @bike]
  end

  def show
    @bike = Bike.find_by(id: params[:id])
    authorize [:profiles, @bike]
    impressionist(@bike)
  rescue ActiveRecord::RecordNotFound, Pundit::NotDefinedError
    redirect_to(profiles_bikes_path, flash: {error: t(:bike_not_found)})
  end

  def create
    @bike = Bike.new(bike_params)
    authorize [:profiles, @bike]

    if session[:pictures].present?
      session[:pictures].each do |picture_id|
        @bike.pictures << Picture.find_by(id: picture_id)
      end
    end

    if @bike.save
      AdminMailer.on_moderation.deliver_later if @bike.original_url.blank?
      session[:pictures] = []
      redirect_to(profiles_bikes_path, flash: {success: t(:bike_created)})
    else
      render :new
    end
  end

  def edit
    @bike = Bike.find_by(id: params[:id])
    authorize [:profiles, @bike]
    session[:bike_id] = @bike.id
  end

  def update
    @bike = Bike.find_by(id: params[:id])
    authorize [:profiles, @bike]

    if @bike.update(bike_params)
      AdminMailer.on_moderation.deliver_later if @bike.original_url.blank?
      session[:pictures] = []
      redirect_to(profiles_bikes_path, flash: {notice: t(:bike_updated)})
    else
      render :edit
    end
  end

  def restore
    @bike = Bike.find_by(id: params[:id])
    authorize [:profiles, @bike]

    if @bike.update(status: :on_moderation)
      AdminMailer.on_moderation.deliver_later
      redirect_to(profiles_bikes_path, flash: {notice: t(:bike_restored)})
    else
      flash[:error] = t(:bike_restored_erorr)
    end
  end

  def close
    @bike = Bike.find_by(id: params[:id])
    authorize [:profiles, @bike]

    if @bike.update(status: :closed)
      redirect_to(profiles_bikes_path, flash: {notice: t(:bike_closed)})
    else
      flash[:error] = t(:bike_closed_error)
    end
  end

  def drop_session_pictures
    if session[:pictures].present?
      session[:pictures].each do |picture_id|
        Picture.find_by(id: picture_id).delete
      end
      session[:pictures] = []
    end
    session[:bike_id] = nil
  end

  def load_city
    @city = City.friendly.find(params.dig(:bike, :city_id)) if params[:bike].present? && params[:bike][:city_id].present?
  end

  private

  def bike_params
    params.require(:bike).permit(
      :title,
      :description,
      :function,
      :suspension,
      :folding,
      :electric,
      :age,
      :sex,
      :gears,
      :wheels,
      :price,
      :city_id,
      :user_id
    )
  end
end

app/controllers/profiles/pictures_controller.rb
class Profiles::PicturesController < ApplicationController
  def destroy
    @picture = Picture.find_by(id: params[:id])
    if @picture.destroy
      session[:pictures] -= [params[:id].to_i] if session[:pictures].present?
      render json: { message: {success: t(:status_update_success)}}
    else
      render json: { message: {alert: t(:status_update_error)}}, status: 400
    end
  end

  def upload
    session[:pictures] ||= []
    picture_id = 0

    if params[:pictures]
      if session[:bike_id].present?
        params[:pictures].each do |picture|
          current_bike = Bike.find_by(id: session[:bike_id])
          if current_bike.pictures.size >= 8
            return false
          else
            bike = current_bike.pictures.create(img: picture)
            picture_id = bike.id
            session[:pictures] << bike.id
          end
        end
      else
        params[:pictures].each do |picture|
          break if session[:pictures].size >= 8
          picture_id = Picture.create(img: picture).id
          picture_id = picture_id
          session[:pictures] << picture_id
        end
      end
    end

    picture_preview = Picture.find_by(id: picture_id)

    # json data for jquery-file-upload
    render json: {
      pictures: session[:pictures], # pictures array
      picture_id: picture_id,
      picture_preview: picture_preview.img.url(:medium_s)
    }
  end
end

app/helpers/bikes_helper.rb
module BikesHelper
  def pretty_date(date)
    if date.today?
      'Размещено сегодня'
    elsif date.to_date == Date.yesterday
      'Размещено вчера'
    else
      l(date, format: '%e %B %Y')
    end
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/bikes/_bike.html.slim
.profile_bike
  .image
    .fotorama.without_thumbs
      - bike.pictures.order(img_updated_at: :asc).each do |picture|
        = image_tag picture.img.url(:medium)
    .status class="#{bike.status}"
      = t("enumerize.defaults.status.#{bike.status}")
  .title = link_to truncate(bike.title, length: 70), profiles_bike_path(bike), target: '_blank'
  .config
    .bike_group
      span Тип велосипеда:
      = t("enumerize.defaults.function.#{bike.function}")

    - if bike.suspension.present?
      .bike_group
        span Подвеска:
        = t("enumerize.defaults.suspension.#{bike.suspension}")

    - if bike.gears.present?
      .bike_group
        span Количество скоростей:
        = bike.gears

    - if bike.wheels.present?
      .bike_group
        span Размер колес:
        = bike.wheels

    - if bike.sex.present?
      .bike_group
        span Пол:
        = t("enumerize.defaults.sex.#{bike.sex}")

  - if bike.description.present?
    .description
      .bike_group
        div Описание:
        = truncate(sanitize(bike.description, tags: %w[br \n]), length: 100)
  .services
    = link_to 'Редактировать', edit_profiles_bike_path(bike), class: 'edit'
    - unless bike.status == :closed
      = link_to 'Снять с продажи', profiles_bike_close_path(bike), method: :post, class: 'close'
    - else
      = link_to 'Вернуть на продажу', profiles_bike_restore_path(bike), method: :post, class: 'restore'

app/views/profiles/bikes/_form.html.slim
.bike_new
  .layout_dropzone
  = simple_form_for [:profiles, @bike], html: {multipart: true} do |f|
    .form_group
      = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
      = f.input :title
    .form_group
      = f.input :description, as: :text
    .form_group
      = f.input :gears, collection: Bike.gears.options, include_blank: 'Выбрать'
    .form_group
      = f.input :wheels, collection: Bike.wheels.options, include_blank: 'Выбрать'
    .form_group
      = f.input :suspension, collection: Bike.suspension.options, include_blank: 'Выбрать'
    .form_group.city
      = f.association :city, as: :select, collection: [ @bike.city || @city ], selected: @city
    .form_group
      = f.input :function, collection: Bike.function.options, include_blank: 'Выбрать'
    .form_group
      = f.input :age, collection: Bike.age.options, include_blank: 'Выбрать'
    .form_group
      = f.input :sex, collection: Bike.sex.options, include_blank: 'Выбрать'
    .form_group.checkbox
      = f.input :folding, as: :boolean
    .form_group.checkbox
      = f.input :electric, as: :boolean
    .form_group
      = f.input :price, as: :string, maxlength: 9, input_html: { class: 'price_mask' }
    .form_group
      = f.input :pictures, as: :file, input_html: { multiple: true, name: 'pictures[]', class: 'file_pictures_original' }
      .dropzone
        .progress_bar data-progress=0
        span Перетащите изображения на форму или выберите их вручную (не более 8 штук)
        .file_pictures Выбрать фото
    .form_group.pictures_list.edit_fields
      - @bike.pictures.each do |picture|
        .fields
          = image_tag picture.img.url(:medium_s)
          .remove_picture data-id=picture.id
    .form_group.actions
      = f.submit 'Сохранить', class: 'save'
      = link_to 'Отменить', profiles_bikes_path, class: 'cancel'

app/views/profiles/bikes/edit.html.slim
.inner_content
  = render 'form'

app/views/profiles/bikes/index.html.slim
.inner_content
  - if @bikes.any?
    = render @bikes
  - else
    .profile_head
      h2 У Вас пока нет объявлений

app/views/profiles/bikes/new.html.slim
.inner_content
  = render 'form'

app/views/profiles/bikes/show.html.slim
.inner_content
  = render 'shared/bike_show', bike: @bike